name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build all packages
        run: yarn build

      - name: Lint check (placeholder)
        run: echo "Add ESLint or type checks here"

      - name: Test placeholder
        run: echo "Add test runner setup here"
